---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: podman
upstream_tag_template: v{version}

packages:
  podman-fedora:
    pkg_tool: fedpkg
    specfile_path: rpm/podman.spec

srpm_build_deps:
  - git-archive-all
  - make

actions:
  fix-spec-file: "bash .packit-copr-rpm.sh"
  pre-sync: "bash .packit-rpm-git-commit.sh"

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [podman-fedora]
    notifications: &packit_generic_failure_notification
      failure_comment:
        message: "packit failure"
    enable_net: true
    targets:
      - fedora-41-x86_64
      - fedora-41-aarch64
      - fedora-42-x86_64
      - fedora-42-aarch64