name: "test"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: get comment
        id: pr
        run: |
          echo "uri=thisisacomment" >> "$GITHUB_OUTPUT"
          echo $uri
      - name: echo
        run: |
          echo ${{ steps.pr.outputs.uri }}
      - name: comment PR link
        uses: thollander/actions-comment-pull-request@v3
        env:
          PR: ${{ steps.pr.outputs.uri }}
        with:
          message: "message1: ${{ steps.pr.outputs.uri }}"
      - name: comment PR link
        uses: thollander/actions-comment-pull-request@v3
        env:
          URI: ${{ steps.pr.outputs.uri }}
        with:
          message: "message2: $URI"
      - name: comment PR link
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: "message3: ${{ steps.pr.outputs.uri }}"


